### ISSUE TITLE
[bug] Contributor instructions have a missing script

### ISSUE THREAD

**Issue by jbs-marcus** [danpacho/tailwindest#102]
**Describe the bug**
The [contributor instructions](https://github.com/danpacho/tailwindest/blob/e3c4bfb5dd9e1bc3a81efb7d5da18d355dfa7439/CONTRIBUTING.md#installation) state that one needs to run `pnpm test:prepublish` but it fails with

```
ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "test:prepublish" not found

Did you mean "pnpm prepublish"?
```

The auto-suggested command seems to work.

**Expected behavior**
`pnpm test:prepublish` to be a script that does something

**Additional context**
- Fedora Linux 40 (KDE Plasma) x86_64
- pnpm 9.0.6

**Comment by danpacho** [comment]
Thank you! I will fix it asap:)

**Comment by danpacho** [comment]
Fixed it.
