### ISSUE TITLE
Incorrect typings for before:content

### ISSUE THREAD

**Issue by davidbalik** [danpacho/tailwindest#13]
Hello, 

first of all, good work with this library, looks awesome 👍 

About the issue. I think I'm doing everything ok, but I'm not able to match defined typings for `::before` and `content` property. See: 

![wind-issue](https://user-images.githubusercontent.com/86349895/210581994-273c5165-f7e9-469f-95e7-154fa6ab93f9.png)

**Comment by danpacho** [comment]
Thank you for your feedback! I'am checking this bug right now🙂! 

It is small type bug, i think👍! 

Lastly let me know on discussion page if you have an idea or feature request about package!
