### ISSUE TITLE
How to use it in React component

### ISSUE THREAD

**Issue by JaLe29** [danpacho/tailwindest#20]
Lets say, I would like to create react component `Button`

```

interface Props {
	customClassName?: string; // I would like to use only tailwind type
	children: any;
	onClick?: () => void;
}

const MyButton: React.FC<Props> = ({ customClassName, children, onClick }) => (
	<button className={customClassName} onClick={onClick}>
		{children}
	</button >
);

export default MyButton;

```

There is a prop `customClassName?: string;` of `string` type. How can I allow **only tailwind classname** insteadof `string` type?

Thank you

**Comment by danpacho** [comment]
Hi! You can easily get full type definition of tailwind classname by using `Tailwindest` type😀.

```ts
type TailwindClass = Tailwindest[keyof Tailwindest]

const yourTailwindClassName: TailwindClass = "rounded-3xl"
```

> **note**
>
> Check out code completion result!
>
> <img width="500" alt="code completion" src="https://user-images.githubusercontent.com/53421296/222935781-d9662020-7446-4799-b81d-9d0bbf6e284a.png">

In this way, you can access the whole type definition of `tailwind` properties. But you can't get nested classnames like **`dark:bg-gray-100`** or **`dark:hover:bg-gray-200`** etc... This is because `tailwindest` uses recursive generics to calculate nested class names in real time.

**Comment by danpacho** [comment]
If you want to add custom properties, defined in `tailwind.config.js`,you can also get your classname in a similar way. 

> **Note**
>
> use `Tailwindest`'s **generic** option for defining custom properties.

```ts
type MyTailwind = Tailwindest<
    {
        color: "custom1" | "custom2" | "custom3"
        // global color palette 
    },
    {
        accentColor: "@custom-accent"
        // accent color palette 
    }
>

export type MyTailwindClass = MyTailwind[keyof MyTailwind]

const myTailwindClassName: MyTailwindClass = "bg-custom3"
```

**Comment by JaLe29** [comment]
I would like to use standard classnames like p-0, pr-0, m-0 etc

**Comment by danpacho** [comment]
```
type StandardTailwindClass = Tailwindest[keyof Tailwindest]

const standardTailwindClassName: StandardTailwindClass = "p-0"
```
Then, you can just use pure `Tailwindest` type for that🙂!

**Comment by JaLe29** [comment]
Nice! Now we can easily enter class names!
