### ISSUE TITLE
Documentation is empty

### ISSUE THREAD

**Issue by JaLe29** [danpacho/tailwindest#25]
Hi,

documentation is empty.

Is documentation build still in progress?

For example
https://tailwindest.vercel.app/2-learn/basic-usage-conditional

![image](https://user-images.githubusercontent.com/22296816/230709592-a51ce9b4-1e78-481e-801e-22c477682e97.png)

**Comment by danpacho** [comment]
Yes, we're working on examples and official documentation right now! It should be ready this week. Have a happy weekend :)

**Comment by danpacho** [comment]
The documentation for version 1.1.0 is all ready! Sorry it took longer than expected😂!
