### ISSUE TITLE
[Question] How to use "white-space"

### ISSUE THREAD

**Issue by JaLe29** [danpacho/tailwindest#38]
**Describe the bug**
How to use "white-space" - https://tailwindcss.com/docs/whitespace in `wind` call?

```
		className={wind({
			... ?
		}).class()}
``` 

Thank you

**Comment by danpacho** [comment]
It is indeed a bug that `whitespace` properties are not defined! Thanks for the good bug report :) Also, `tailwindest` version 2 RC has been released, please try it if you have a time to check out!🙂 Bug will be fixed in an hour, happy coding!

**Comment by danpacho** [comment]
Bug fixed!
Please install latest version of tailwindest
```bash
pnpm I tailwindest@latest
```

**Comment by JaLe29** [comment]
Thank you!
